name: CI/CD
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
jobs:
    build-and-test:
        name: Build the project
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Run eslint
              run: npm run lint
            - name: Test and coverage
              run: npm run test
              env:
                DB_HOST: ${{ secrets.TEST_DB_HOST }}
                DB_PORT: ${{ secrets.TEST_DB_PORT }}
                DB_USERNAME: ${{ secrets.TEST_DB_USERNAME }}
                DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
                DB_NAME: ${{ secrets.TEST_DB_NAME }}
                REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
                JWKS_URI: ${{ secrets.JWKS_URI }}
                PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
            - name: Build-ts
              run: npm run build
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    echo:
        name: Echo
        runs-on: ubuntu-latest
        needs: build-and-test
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Echo a message
              run: echo "Hello, World! This is a message from the echo job."
